### ISSUE TITLE
Toolbar is added even when plugin is disabled

### ISSUE THREAD

**Issue by AsgerPetersen** [erpas/serval#11]
Steps to reproduce:

1. Install Serval and check that the Serval toolbar shows up in the GUI
2. Disable Serval plugin (Click `Plugins -> Manage and install plugins... -> Installed` and then uncheck Serval). Check that Serval toolbar disappears from GUI
3. Restart QGIS
4. Now the Serval toolbar is present in the GUI. (And the plugin is still unchecked in the plugin manager)

Serval version: 0.8.1
QGIS version: 2.16.2 on OSX

Thank you for a very nice plugin!

**Comment by erpas** [comment]
Thanks Asger for pointing this out! Will be fixed in the next release - hopefully this year...

**Comment by erpas** [comment]
Fixed in ver 3.0.
