### ISSUE TITLE
To improve the plugin

### ISSUE THREAD

**Issue by Arkads-PL** [erpas/serval#13]
I'm searching for a tool to modify raster values along a line/polyline with values at ends of lines/polyline taken from raster. Second goal for me is a tool which can change the raster cells between two lines/polylines simmilar length. The lines can be approximately parallel. New values for raster cells should be assigned only for cells between these lines/polylines but not for raster cells along these two lines. The raster cells along these two lines are the base/boundary condition of interpolation.

Maybe it is possible to improve the plugin and expand it for similar purpose.

**Comment by erpas** [comment]
Thanks for suggestions!

**Comment by ppopoca** [comment]
Hi, thanks for the plugin, it's really useful. An amazing feature would be the capability to change the values not from RGB bands, but for any band loaded into the RGB channels. This way it'd be possible to edit multispectral rasters.

**Comment by erpas** [comment]
@ppopoca thanks for suggestion! Thinking about possible solution, how many bands do you have?

**Comment by erpas** [comment]
Version 3.10.0 is out with features you suggested.
It needs to be documented and released to the official QGIS plugins repo.

@Arkads-PL 
You can now select parts of your raster to be changed and interpolate on a mesh or vector layer to achieve what you suggested.

@ppopoca 
Version 3.10.0 can operate on a single band of multiband raster as you suggested.

Again, thanks for your suggestions!

**Comment by ppopoca** [comment]
Greetings Radosław!

Amazing news! Thanks for the info!

Stay safe.
__
Pavel Popoca Cruz
