### ISSUE TITLE
change value of cell not pixel

### ISSUE THREAD

**Issue by GlobalConservationist** [erpas/serval#14]
I'm trying to edit the values of cells in my grid but Serval changes the value of pixels within the cell, not the value of the whole cell. I have my grid (a tiff) selected, when I click in a cell (either with display or draw/edit mode) I can change the value, but it changes it a of the single pixel I'm on, not the cell I'm in. Is this intended behaviour? Or am I doing something wrong?

**Comment by erpas** [comment]
Could you please explain the difference between raster cell and pixel?
