### ISSUE TITLE
Possibility to join efforts with ThRasE plugin

### ISSUE THREAD

**Issue by XavierCLL** [erpas/serval#19]
Hi Radosław,

I recently developed a new plugin ThRasE is a Thematic Raster Editor (https://github.com/SMByC/ThRasE) similar but with others features, Paolo here https://github.com/SMByC/ThRasE/issues/1 ask for join the efforts, I think that it is a good idea, what do you think?

Best regards,
Xavier

**Comment by erpas** [comment]
Hi Xavier,

Sorry for the delayed answer... Serval deals with all kind of raster data types. While ThRasE has great manipulation and selection tools, what are chances that we could use it for non-integer values? Have you ever planned that?

Best regards,
Radek

**Comment by XavierCLL** [comment]
Hi Radek,

Yeah, you are right, that is the difference, right now ThRasE only works for integer values (it is the idea of the plugin: for edit thematic rasters) and for the moment I do not plan to add support for non-integer values.

Regards,
Xavier
