### ISSUE TITLE
On Windows Python crashes when QGIS is closing

### ISSUE THREAD

**Issue by erpas** [erpas/serval#2]
On Windows objects of GDAL Python API are not properly deleted on plugin unload and that causes Python to crash when QGIS is closing.

**Comment by saberraz** [comment]
Confirmed with QGIS 2.14

**Comment by saberraz** [comment]
Works fine in version 0.8 under windows with QGIS 2.14

**Comment by erpas** [comment]
This issue found its workaround in version 0.8.
