### ISSUE TITLE
Perhaps useful suggestion

### ISSUE THREAD

**Issue by diogoamore** [erpas/serval#22]
First: Great tool! Well done!

As for an improvement suggestion. It would be very time-saving to be able to click and hold-and-drag across a series of pixels rather than having to click on every pixel of interest with the value-copying pencil tool. Not sure whether too costly to implement.

Anyhow, great tool, 
Cheers

**Comment by johnniehard** [comment]
This in combination with ability to change the brush size to be larger than a single pixel would be really useful.

**Comment by erpas** [comment]
Thanks for suggestions! I will keep them in mind :-)

**Comment by erpas** [comment]
Version 3.10.0 is relesed for testing purposes. It will be published to the official QGIS plugins repository once tested and properly documented. Feel free to give it a try.

@diogoamore 
With it you can select raster cell by lines or polygons and then apply new values. Hope that would work for you.

@johnniehard 
Line selection tool has configurable width. 

Thanks for suggestions!
