### ISSUE TITLE
Plugin does not work in QGIS 3.10 - cannot change values

### ISSUE THREAD

**Issue by 1geo1** [erpas/serval#24]
Hi, 

I want to use the serval plugin in qgis 3.1 on mac to modify the values in some raster cells (asc).
I was able to download the plugin and the probing mode is showing me the the cell values. But I cannot modify anything. I tried it with different data, a restart, reinstalling... Always the same result. I have no idea what the problem is.

**Comment by erpas** [comment]
Try to save your raster to a different format, i.e. TIF and try again.
