### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by pyremy** [erpas/serval#27]
Hello, 

recently you added some great features to your plugin (band selection, vector tools)
do you planned to add :
 - some different pencil sizes (1 * 1 , 5 * 5, 10 * 10, 20 * 20)
 - work in editing session like QGIS core editing session

In my concern these features will well completed your plugin but they may not match with your vision.

Regards

**Comment by luislizcano** [comment]
That would be great. I realized that the pencil size in the newer version is bigger than pixel sizes and I don't know how to correct that, I want to modifiy individual pixels as well, but haven't been able.

**Comment by erpas** [comment]
Thanks for suggestions! 

We do not plan to add any custom pencil sizes.
I would suggest to use the line selection tool with line width set according to your needs.

![obraz](https://user-images.githubusercontent.com/3106699/114274761-460fbe80-9a20-11eb-9587-000a85ae6909.png)

This way you can select multiple raster cells in a convenient way and apply a new value to them.

@luislizcano you can change the selection width units as shown above.
