### ISSUE TITLE
Unable to change values

### ISSUE THREAD

**Issue by tedrigby** [erpas/serval#28]
Hi

I am running W10 and QGIS 3.16.4 and recently installed serval to modify some cells in my ascii grid topography file. I have tried all of the recommended selection and reset approaches mentioned in the manual but although the blue circle appears as if it is changing the elevation value - applying the probe to check afterward shows no change. Is there a problem or have I just not approached selection/adjustment in the right order? It is as if the ascii grid file is not available for writing.

Many thanks

Ted Rigby

**Comment by erpas** [comment]
Hi Tom,

yep, the ASCII grid is a read-only format: https://gdal.org/drivers/raster/aaigrid.html#raster-aaigrid
Try to convert it to another format, for example TIF, and you should be able to modify it.

Kind Regards,

Radek Pasiok

**Comment by tedrigby** [comment]
Thanks Radek

I tried  converting  to geotiff  and yes serval then worked fine. Thanks for your speedy response.

Is there some reason why QGIS/Serval does not support writing to an ascii grid – seems odd given the wide use of ascii grid formats in civil engineering as an elevation layer.
I am a split Global Mapper – QGIS user  and can easily export a non ascii raster to ascii grid format in Global Mapper so was not expecting problems writing to a grid in QGIS/Serval?

Ted

**Comment by erpas** [comment]
QGIS depends on GDAL in it, so it would be question for its developers.
