### ISSUE TITLE
I can't use the toolbar

### ISSUE THREAD

**Issue by SvSz** [erpas/serval#29]
Why is it grey for me? I can't use the tool / toolbar

![qgis3](https://user-images.githubusercontent.com/78486927/114020581-0b672400-9870-11eb-9982-11af382e1730.jpg)

**Comment by erpas** [comment]
Please load a raster layer to enable the toolbar actions.

**Comment by erpas** [comment]
For developer:  enable main menu actions even with no raster layer loaded.

**Comment by SvSz** [comment]
thanks very much for your quick reply! I also had to many toolbars active. just right-click and untick some of them!
