### ISSUE TITLE
Serval-generated new pixel size larger than original

### ISSUE THREAD

**Issue by diogoamore** [erpas/serval#33]
Dear all,

As I attempt to duplicate the pixel within my raster file, the new pixel becomes far larger than the original one. More precisely, whether I try the process in a 1m-, 5m- or 12m-pixel-resolution raster, the resulting new pixel always becomes a 200m-ish large pixel. I am trying the earliest Serval version on QGis 3.16. Any possible explanation for this? Image attached.

Cheers

Diogo

![serval_issue](https://user-images.githubusercontent.com/39138440/133866883-67fb70b3-e4ba-46a7-96a9-61dd9685424a.jpeg)

**Comment by erpas** [comment]
Hi Diogo,

It is generally suggested to use a projected CRS, not WGS-84. 
Try to load your raster to a project with a projected CRS and see the difference.

Good luck

Radek

**Comment by diogoamore** [comment]
Thanks for the feedback. The problem has been accidentally solved by trial and error. It seems that within the laptop being used at that moment the Serval version had to be downgraded from 3.10 to 3.01 so it worked properly for any version of QGIS. Seems it was a plugin version conflict. 

Thanks for the support
