### ISSUE TITLE
Problems with the raster layer file format

### ISSUE THREAD

**Issue by edenyul97** [erpas/serval#34]
Hello!

I have tested Serval in QGIS version 3.10.14-1 using asc files.
The Serval seemed to work, but the value was not actually changed.
I was confused because there was no mention of the asc file in QGIS or the GitHub wiki.
However, I found that It works well after converting the file to tiff

So I suggest you to add the relevant guide to GitHub wiki, or add the following phrase after line 682 of the serval.py
os.path.splitext(layer.source())[1].lower()!='.asc'

**Comment by erpas** [comment]
Solved in 3.10.3
