### ISSUE TITLE
Python error if selecting a non-valid raster

### ISSUE THREAD

**Issue by nicogodet** [erpas/serval#40]
```
\Serval\utils.py", line 100, in check_gdal_driver_create_option
    band = dataset.GetRasterBand(1)
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'
```

Happens if a raster has a broken path (temp raster from previous QGIS instance that non longer exist)

**Comment by erpas** [comment]
Hi @nicogodet,

Thanks for reporting it!
Fixed in version 3.10.5 of the plugin - it currently awaits update approval.
