### ISSUE TITLE
Probe default behaviour

### ISSUE THREAD

**Issue by saberraz** [erpas/serval#8]
I think the probe action should be done without the need from user to click. The value in the box should be updated as user moves the mouse over the cell values???

**Comment by erpas** [comment]
The probe tool is thought to act as a pipette - so you can store pixel value to apply it to some other cell(s). Would be difficult to keep the values if they would change with every mouse move.

To see pixel values while moving over a raster, users can use the ValueTool plugin [1].

[1] http://plugins.qgis.org/plugins/valuetool/
